#!/bin/bash

REG=$4
if [ ! $4 ]; then
  #echo "Warning: No REG found... Using own's REG"
  REG="aiMonkey"
fi
echo "####################### $REG VERSION FILE #############################"
echo ""
echo ""

#
BRANCH=$1
if [ ! $1 ]; then
  echo "Warning: No branch given... Using main"
  BRANCH="main"
fi

TRIGGER=$2
if [ ! $2 ]; then
  echo "Warning: No trigger given... Using continuos $2"
  TRIGGER="continuos"
fi
#
TIME_STAMP=$3
if [ ! $3 ]; then
  echo "Warning: No timestamp given... Using own's timestamp"
  TIME_STAMP=$(date +%s)
fi
#
bash _vextract.sh
#

VER=$(cat VERSION | tr -d '\n')
BUILD=$(cat BUILD_NR | tr -d '\n')
BDAY=$(cat BDAY | tr -d '\n')
CDAY=$(cat CDAY | tr -d '\n')
#
bash _codeName.sh $BDAY 1 $CDAY
#
COLOR=$(cat CDAY | tr -d '\n')
CNAME=$(cat CNFILE | tr -d '\n')
##
#
VERFILE="versionFile.js"
rm -rf $VERFILE
#
echo "//autogenerated, do not set values\n" >> $VERFILE
echo "export const version = '"$VER"'" >> $VERFILE
echo "export const build = '"$TIME_STAMP"'" >> $VERFILE
echo "export const shortBuild = '"$BUILD"'" >> $VERFILE
echo "export const codeName = '"$CNAME"'" >> $VERFILE
echo "export const color = '"$COLOR"'" >> $VERFILE
echo "export const branch = '"$BRANCH"'" >> $VERFILE
echo "export const trigger = '"$TRIGGER"'" >> $VERFILE
#
echo "VERSION FILE: "
#copy the versionFile.js
cat $VERFILE
cp $VERFILE ../../src/$VERFILE

#
echo ""
echo ""
